title: Stoza Codes
email: stoza@stoza.codes
description: >- # this means to ignore newlines until "baseurl:"
  The home page for Dan Stoza's coding adventures, including the Tavern VTT
url: "https://stoza.codes" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dstoza

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
show_downloads: false

github:
  is_project_page: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
